# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import group_builder.apps.mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170615_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
        migrations.RemoveField(
            model_name='group',
            name='published_date',
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lft',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=group_builder.apps.mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='rght',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='tree_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
