# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20170619_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
