# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import group_builder.apps.mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0009_auto_20170619_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', group_builder.apps.mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
